### ISSUE TITLE
Roll

### ISSUE THREAD

**Issue by matiasnoriega** [sysarmy/notperlbot#1]
Que `!roll XdY` devuelva el resultado random de X dados de Y caras cada uno.

**Comment by edux** [comment]
Hay que checkear bien el input con una regex porque ?roll 3 se va de viaje.

11:49:58 ERROR    errbot.core               An error happened while processing a message ("?roll 3"): Traceback (most recent call last):
  File "/Users/eduardo/e/notperlbot/virtualenv/lib/python3.8/site-packages/errbot/core.py", line 454, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/Users/eduardo/e/notperlbot/errbot/plugins/roll/roll.py", line 14, in roll
    if not numbers[1].isdigit() == True or numbers[1] == '0':
IndexError: list index out of range
"
Traceback (most recent call last):
  File "/Users/eduardo/e/notperlbot/virtualenv/lib/python3.8/site-packages/errbot/core.py", line 454, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/Users/eduardo/e/notperlbot/errbot/plugins/roll/roll.py", line 14, in roll
    if not numbers[1].isdigit() == True or numbers[1] == '0':
IndexError: list index out of range
